/*
Magnitude Analysis

Purpose:
- To quantify data and analyze totals or averages across different dimensions.
- To understand data distribution across categories.

SQL Concepts Used:
- Aggregate Functions: SUM(), COUNT(), AVG()
- GROUP BY, ORDER BY, JOIN
*/

-- 1. Total customers by country
SELECT
    country,
    COUNT(customer_id) AS total_customers
FROM [gold.dim_customers]
GROUP BY country
ORDER BY total_customers DESC;

-- 2. Total customers by gender
SELECT
    gender,
    COUNT(customer_id) AS total_customers
FROM [gold.dim_customers]
GROUP BY gender
ORDER BY total_customers DESC;

-- 3. Total products by category
SELECT
    category,
    COUNT(product_id) AS total_products
FROM [gold.dim_products]
GROUP BY category
ORDER BY total_products DESC;

-- 4. Average product cost by category
SELECT
    category,
    AVG(cost) AS avg_cost
FROM [gold.dim_products]
GROUP BY category
ORDER BY avg_cost DESC;

-- 5. Total revenue generated by each product category
SELECT
    dp.category,
    SUM(fs.sales_amount) AS total_revenue
FROM [gold.fact_sales] fs
LEFT JOIN [gold.dim_products] dp
    ON dp.product_key = fs.product_key
GROUP BY dp.category
ORDER BY total_revenue DESC;

-- 6. Total revenue generated by each customer
SELECT
    dc.customer_key,
    dc.first_name,
    dc.last_name,
    SUM(fs.sales_amount) AS total_revenue
FROM [gold.fact_sales] fs
LEFT JOIN [gold.dim_customers] dc
    ON dc.customer_key = fs.customer_key
GROUP BY 
    dc.customer_key,
    dc.first_name,
    dc.last_name
ORDER BY total_revenue DESC;

-- 7. Total quantity of items sold by country
SELECT
    dc.country,
    SUM(fs.quantity) AS total_sold_items
FROM [gold.fact_sales] fs
LEFT JOIN [gold.dim_customers] dc
    ON dc.customer_key = fs.customer_key
GROUP BY dc.country
ORDER BY total_sold_items DESC;
